name: CI/CD for Angular app on Node 16

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16

jobs:
  Angular:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node 16
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app
      run: npm run build

    - name: Test Angular app
      run: npm test -- --watch=false --browsers=ChromeHeadless
